### ISSUE TITLE
JavaScript Build Setup in wordpress

### ISSUE THREAD

**Issue by shinji19** [solaito/watts#2]
https://ja.wordpress.org/team/handbook/block-editor/how-to-guides/javascript/js-build-setup/

**Comment by solaito** [comment]
> @wordpress/scripts パッケージはこれらのライブラリーを標準化されたシンプルな開発に抽象化します。このため webpack や babel を細かく構成する必要はありません。構成の詳細については @wordpress/scripts パッケージのドキュメントを参照してください。
それっぽいけど、ブロックエディターを開発するときの話なのかなと思った。

**Comment by shinji19** [comment]
確かにブロックエディターのハンドブックだった

**Comment by solaito** [comment]
とりあえずIE対応は諦めて、「WPが管理画面でサポートしている程度にはレガシーなブラウザに対応する」（プラグインのJSをwp-scriptsでビルドする）という方針にする。
なので追々wp-scriptsを使ったビルドスクリプトも書きます。
